int run(string str);
string hat(char c);
string nose(char c);
string left_eye(char c);
string right_eye(char c);
string left_arm(char c);
string right_arm(char c);
string torso(char c);
string base(char c);